-- ===============================================================
-- CLIMATE DATA REPOSITORY (CDR) - ORACLE 21c SCHEMA
-- ===============================================================

-- 1. Create Tables with Partitioning
CREATE TABLE climate_stations (
    station_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    station_name VARCHAR2(100) NOT NULL,
    city VARCHAR2(50) NOT NULL,
    country VARCHAR2(50) NOT NULL,
    latitude NUMBER(9,6),
    longitude NUMBER(9,6),
    elevation_m NUMBER(6,2),
    install_date DATE,
    is_active NUMBER(1) DEFAULT 1
);

CREATE TABLE sensors (
    sensor_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    station_id NUMBER REFERENCES climate_stations(station_id),
    sensor_type VARCHAR2(50) NOT NULL,
    unit_of_measure VARCHAR2(20),
    calibration_date DATE,
    is_operational NUMBER(1) DEFAULT 1
);

CREATE TABLE weather_readings (
    reading_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    sensor_id NUMBER REFERENCES sensors(sensor_id),
    station_id NUMBER REFERENCES climate_stations(station_id),
    reading_date DATE NOT NULL,
    temperature_c NUMBER(5,2),
    humidity_pct NUMBER(5,2),
    precipitation_mm NUMBER(7,2),
    wind_speed_kmh NUMBER(5,2),
    pressure_hpa NUMBER(7,2),
    CONSTRAINT pk_weather_readings PRIMARY KEY (reading_id, reading_date)
)
PARTITION BY RANGE (reading_date) INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
(
    PARTITION p_initial VALUES LESS THAN (TO_DATE('2023-01-01', 'YYYY-MM-DD'))
);

CREATE TABLE env_readings (
    env_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    station_id NUMBER REFERENCES climate_stations(station_id),
    reading_date DATE NOT NULL,
    co2_ppm NUMBER(7,2),
    pm25 NUMBER(7,2),
    pm10 NUMBER(7,2),
    aqi NUMBER(4),
    CONSTRAINT pk_env_readings PRIMARY KEY (env_id, reading_date)
)
PARTITION BY RANGE (reading_date) INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
(
    PARTITION p_env_initial VALUES LESS THAN (TO_DATE('2023-01-01', 'YYYY-MM-DD'))
);

CREATE TABLE alerts (
    alert_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    station_id NUMBER REFERENCES climate_stations(station_id),
    alert_type VARCHAR2(50),
    alert_message VARCHAR2(500),
    triggered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    severity VARCHAR2(20) CHECK (severity IN ('Low', 'Medium', 'High', 'Critical')),
    is_resolved NUMBER(1) DEFAULT 0
);

CREATE TABLE audit_log (
    log_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name VARCHAR2(50),
    action VARCHAR2(20),
    changed_by VARCHAR2(100),
    changed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    old_values CLOB,
    new_values CLOB
);

-- 2. PL/SQL Package
CREATE OR REPLACE PACKAGE cdr_pkg AS
    FUNCTION get_avg_temp(p_station_id NUMBER, p_year NUMBER) RETURN NUMBER;
    PROCEDURE generate_station_report(p_station_id NUMBER);
    PROCEDURE check_alerts(p_reading_id NUMBER);
END cdr_pkg;
/

CREATE OR REPLACE PACKAGE BODY cdr_pkg AS
    FUNCTION get_avg_temp(p_station_id NUMBER, p_year NUMBER) RETURN NUMBER IS
        v_avg_temp NUMBER;
    BEGIN
        SELECT AVG(temperature_c) INTO v_avg_temp
        FROM weather_readings
        WHERE station_id = p_station_id
        AND EXTRACT(YEAR FROM reading_date) = p_year;
        RETURN v_avg_temp;
    END get_avg_temp;

    PROCEDURE generate_station_report(p_station_id NUMBER) IS
    BEGIN
        -- Logic for report generation
        NULL;
    END generate_station_report;

    PROCEDURE check_alerts(p_reading_id NUMBER) IS
        v_temp NUMBER;
        v_station_id NUMBER;
    BEGIN
        SELECT temperature_c, station_id INTO v_temp, v_station_id
        FROM weather_readings WHERE reading_id = p_reading_id;
        
        IF v_temp > 40 THEN
            INSERT INTO alerts (station_id, alert_type, alert_message, severity)
            VALUES (v_station_id, 'High Temp', 'Temperature exceeded 40C', 'High');
        END IF;
    END check_alerts;
END cdr_pkg;
/

-- 3. Triggers
CREATE OR REPLACE TRIGGER trg_weather_alert
AFTER INSERT ON weather_readings
FOR EACH ROW
BEGIN
    IF :NEW.temperature_c > 40 THEN
        INSERT INTO alerts (station_id, alert_type, alert_message, severity)
        VALUES (:NEW.station_id, 'High Temp', 'Auto-alert: Temp > 40C', 'High');
    END IF;
END;
/

-- 4. Materialized Views
CREATE MATERIALIZED VIEW mv_monthly_climate
BUILD IMMEDIATE
REFRESH COMPLETE ON DEMAND
AS
SELECT station_id, 
       TRUNC(reading_date, 'MM') as month,
       AVG(temperature_c) as avg_temp,
       SUM(precipitation_mm) as total_rain
FROM weather_readings
GROUP BY station_id, TRUNC(reading_date, 'MM');

-- 5. Roles and Security
-- CREATE ROLE cdr_admin;
-- CREATE ROLE cdr_analyst;
-- CREATE ROLE cdr_readonly;

-- 6. Object-Oriented Database (OODB) Features
CREATE OR REPLACE TYPE location_typ AS OBJECT (
    city VARCHAR2(50),
    country VARCHAR2(50),
    latitude NUMBER(9,6),
    longitude NUMBER(9,6)
);
/

-- Update climate_stations to use Object Type (Conceptual for OODB demonstration)
-- ALTER TABLE climate_stations ADD (loc_obj location_typ);

-- 7. Extraction / Loader (External Table Definition)
-- This assumes a CSV file 'weather_data.csv' exists in the 'DATA_PUMP_DIR'
/*
CREATE TABLE weather_readings_ext (
    reading_date DATE,
    temp NUMBER,
    humidity NUMBER
)
ORGANIZATION EXTERNAL (
    TYPE ORACLE_LOADER
    DEFAULT DIRECTORY DATA_PUMP_DIR
    ACCESS PARAMETERS (
        RECORDS DELIMITED BY NEWLINE
        FIELDS TERMINATED BY ','
    )
    LOCATION ('weather_data.csv')
);
*/

-- 8. Auditory (Fine-Grained Auditing)
-- Enable standard auditing on sensitive tables
-- AUDIT INSERT, UPDATE, DELETE ON weather_readings BY ACCESS;

-- 9. Summary (Advanced Materialized Views)
CREATE MATERIALIZED VIEW mv_annual_summary
BUILD IMMEDIATE
REFRESH FAST ON COMMIT
AS
SELECT station_id,
       EXTRACT(YEAR FROM reading_date) as year,
       AVG(temperature_c) as avg_annual_temp,
       MAX(temperature_c) as max_temp,
       MIN(temperature_c) as min_temp
FROM weather_readings
GROUP BY station_id, EXTRACT(YEAR FROM reading_date);

-- 10. Allocate & Fragmentation (DBA Scripts)
-- Script to check for table fragmentation
/*
SELECT table_name, 
       round((blocks*8),2)||'kb' "Fragmented Size", 
       round((num_rows*avg_row_len/1024),2)||'kb' "Actual Size"
FROM user_tables
WHERE table_name = 'WEATHER_READINGS';

-- Command to deallocate unused space
-- ALTER TABLE weather_readings DEALLOCATE UNUSED;
*/

-- 12. Advanced Indexing (Database Manager Persona)
-- B-Tree Index for range queries on date
CREATE INDEX idx_weather_date ON weather_readings(reading_date);

-- Bitmap Index for low-cardinality columns (e.g., station_id if few stations)
CREATE BITMAP INDEX idx_station_status ON climate_stations(is_active);

-- Function-Based Index for case-insensitive searches
CREATE INDEX idx_station_name_upper ON climate_stations(UPPER(station_name));

-- 13. Analytical SQL & Window Functions
-- Moving Average Calculation (Conceptual)
/*
SELECT reading_date, temperature_c,
       AVG(temperature_c) OVER (
           PARTITION BY station_id 
           ORDER BY reading_date 
           ROWS BETWEEN 6 PRECEDING AND CURRENT ROW
       ) as moving_avg_7day
FROM weather_readings;
*/

-- 14. Virtual Private Database (VPD) Simulation
-- Conceptual: Restrict analysts to only see data from their assigned region
/*
BEGIN
  DBMS_RLS.ADD_POLICY (
    object_schema    => 'CDR_ADMIN',
    object_name      => 'WEATHER_READINGS',
    policy_name      => 'regional_access_policy',
    function_schema  => 'CDR_ADMIN',
    policy_function  => 'get_regional_predicate',
    statement_types  => 'SELECT'
  );
END;
*/

-- 15. Real-time Data Management (Oracle Advanced Queuing)
-- Conceptual: Use AQ for real-time sensor data ingestion
/*
BEGIN
  DBMS_AQADM.CREATE_QUEUE_TABLE (
    queue_table          => 'sensor_data_qt',
    queue_payload_type   => 'location_typ'
  );
  DBMS_AQADM.CREATE_QUEUE (
    queue_name           => 'sensor_data_q',
    queue_table          => 'sensor_data_qt'
  );
  DBMS_AQADM.START_QUEUE (queue_name => 'sensor_data_q');
END;
*/
